TRUNCATE TABLE project.orders_goods CASCADE;
TRUNCATE TABLE project.points_employees CASCADE;
TRUNCATE TABLE project.orders CASCADE;
TRUNCATE TABLE project.clients CASCADE;
TRUNCATE TABLE project.points CASCADE;
TRUNCATE TABLE project.quarantine CASCADE;
TRUNCATE TABLE project.goods CASCADE;
TRUNCATE TABLE project.sellers CASCADE;
TRUNCATE TABLE project.employees CASCADE;
